### ISSUE TITLE
Configure nexus && IntegrationPlatform

### ISSUE THREAD

**Issue by agiertli** [agiertli/rhte-camelk-lab-setup#3]
Right now, we install nexus, but there is no easy declarative way how to configure it - i.e. how to add custom repository (i.e. camelk)

Explore possibilities how to configure nexus
https://github.com/rht-labs/ubiquitous-journey/blob/main/ubiquitous-journey/values-tooling.yaml
https://github.com/redhat-cop/helm-charts/blob/master/charts/sonatype-nexus/templates/config-nexus.txt
https://camel.apache.org/camel-k/1.10.x/architecture/cr/integration-platform.html
https://camel.apache.org/camel-k/1.10.x/configuration/maven.html

- [ ] Configure nexus with red hat repositories https://maven.repository.redhat.com/ga/org/apache/
- [ ] Create a custom "proxy" type of repository (i.e. camelk) - it should proxy maven central and red hat repo
- [ ] Create IntegrationPlatform in tooling namespace which would be configured with custom settings.xml. Settings.xml would be configured to proxy _everything_ via our nexus repo.

This is a typical requirement at most customers and we've had it implemented even at MO. So we should be able to showcase it for the lab as well - as it's definitely "beyond demo" feature.

**Comment by MazArslan** [comment]
is this still an issue, As we have now removed nexus?

**Comment by agiertli** [comment]
Let's close this. Unless you are feeling particularly courageous and want to give it a try ;)
